<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sibusisos-MBP" name="inspiredtesting.services.TestRunner" tests="3" failures="1" timestamp="21 Jul 2021 13:10:38 GMT" time="4.779" errors="0">
  <testcase name="scenario" time="0.812" classname="inspiredtesting.services.TestRunner"/>
  <testcase name="scenario" time="1.106" classname="inspiredtesting.services.TestRunner"/>
  <testcase name="scenario" time="2.861" classname="inspiredtesting.services.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [203] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [203] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at inspiredtesting.services.stepdefs.APIStepDefs.iReceiveAValidHTTPResponseCode(APIStepDefs.java:39)
	at âœ½.I receive a valid HTTP response code "203"(file:///Users/sibusiso87rn/IdeaProjects/automation-framework/services-framework/src/test/resources/features/Users.feature:7)
]]>
    </failure>
  </testcase> <!-- scenario -->
</testsuite> <!-- inspiredtesting.services.TestRunner -->
